
import { RussianWord } from './types';

export const INITIAL_WORDS: RussianWord[] = [
  // LES 50 VERBES ESSENTIELS
  { id: 'v1', russian: 'Быть', french: 'Être', phonetic: 'Byt\'', category: 'verbs' },
  { id: 'v2', russian: 'Иметь', french: 'Avoir', phonetic: 'Imet\'', category: 'verbs' },
  { id: 'v3', russian: 'Делать', french: 'Faire', phonetic: 'Delat\'', category: 'verbs' },
  { id: 'v4', russian: 'Мочь', french: 'Pouvoir', phonetic: 'Moch\'', category: 'verbs' },
  { id: 'v5', russian: 'Хотеть', french: 'Vouloir', phonetic: 'Khotet\'', category: 'verbs' },
  { id: 'v6', russian: 'Должен', french: 'Devoir', phonetic: 'Dolzhen', category: 'verbs' },
  { id: 'v7', russian: 'Знать', french: 'Savoir', phonetic: 'Znat\'', category: 'verbs' },
  { id: 'v8', russian: 'Нужно', french: 'Falloir', phonetic: 'Nuzhno', category: 'verbs' },
  { id: 'v9', russian: 'Идти', french: 'Aller', phonetic: 'Idti', category: 'verbs' },
  { id: 'v10', russian: 'Приходить', french: 'Venir', phonetic: 'Prikhodit\'', category: 'verbs' },
  { id: 'v11', russian: 'Уходить', french: 'Partir', phonetic: 'Ukhodit\'', category: 'verbs' },
  { id: 'v12', russian: 'Приезжать', french: 'Arriver', phonetic: 'Priyezzhat\'', category: 'verbs' },
  { id: 'v13', russian: 'Гулять', french: 'Marcher / Se promener', phonetic: 'Gulyat\'', category: 'verbs' },
  { id: 'v14', russian: 'Бежать', french: 'Courir', phonetic: 'Bezhat\'', category: 'verbs' },
  { id: 'v15', russian: 'Входить', french: 'Entrer', phonetic: 'Vkhodit\'', category: 'verbs' },
  { id: 'v16', russian: 'Выходить', french: 'Sortir', phonetic: 'Vykhodit\'', category: 'verbs' },
  { id: 'v17', russian: 'Путешествовать', french: 'Voyager', phonetic: 'Puteshestvovat\'', category: 'verbs' },
  { id: 'v18', russian: 'Оставаться', french: 'Rester', phonetic: 'Ostavat\'sya', category: 'verbs' },
  { id: 'v19', russian: 'Сказать', french: 'Dire', phonetic: 'Skazat\'', category: 'verbs' },
  { id: 'v20', russian: 'Говорить', french: 'Parler', phonetic: 'Govorit\'', category: 'verbs' },
  { id: 'v21', russian: 'Спрашивать', french: 'Demander', phonetic: 'Sprashivat\'', category: 'verbs' },
  { id: 'v22', russian: 'Отвечать', french: 'Répondre', phonetic: 'Otvechat\'', category: 'verbs' },
  { id: 'v23', russian: 'Думать', french: 'Penser', phonetic: 'Dumat\'', category: 'verbs' },
  { id: 'v24', russian: 'Понимать', french: 'Comprendre', phonetic: 'Ponimat\'', category: 'verbs' },
  { id: 'v25', russian: 'Учить', french: 'Apprendre', phonetic: 'Uchit\'', category: 'verbs' },
  { id: 'v26', russian: 'Забывать', french: 'Oublier', phonetic: 'Zabyvat\'', category: 'verbs' },
  { id: 'v27', russian: 'Верить', french: 'Croire', phonetic: 'Verit\'', category: 'verbs' },
  { id: 'v28', russian: 'Слушать', french: 'Écouter', phonetic: 'Slushat\'', category: 'verbs' },
  { id: 'v29', russian: 'Есть', french: 'Manger', phonetic: 'Yest\'', category: 'verbs' },
  { id: 'v30', russian: 'Пить', french: 'Boire', phonetic: 'Pit\'', category: 'verbs' },
  { id: 'v31', russian: 'Спать', french: 'Dormir', phonetic: 'Spat\'', category: 'verbs' },
  { id: 'v32', russian: 'Просыпаться', french: 'Se réveiller', phonetic: 'Prosypat\'sya', category: 'verbs' },
  { id: 'v33', russian: 'Работать', french: 'Travailler', phonetic: 'Rabotat\'', category: 'verbs' },
  { id: 'v34', russian: 'Покупать', french: 'Acheter', phonetic: 'Pokupat\'', category: 'verbs' },
  { id: 'v35', russian: 'Платить', french: 'Payer', phonetic: 'Platit\'', category: 'verbs' },
  { id: 'v36', russian: 'Использовать', french: 'Utiliser', phonetic: 'Ispol\'zovat\'', category: 'verbs' },
  { id: 'v37', russian: 'Искать', french: 'Chercher', phonetic: 'Iskat\'', category: 'verbs' },
  { id: 'v38', russian: 'Находить', french: 'Trouver', phonetic: 'Nakhodit\'', category: 'verbs' },
  { id: 'v39', russian: 'Давать', french: 'Donner', phonetic: 'Davat\'', category: 'verbs' },
  { id: 'v40', russian: 'Брать', french: 'Prendre', phonetic: 'Brat\'', category: 'verbs' },
  { id: 'v41', russian: 'Положить', french: 'Mettre', phonetic: 'Polozhit\'', category: 'verbs' },
  { id: 'v42', russian: 'Открыть', french: 'Ouvrir', phonetic: 'Otkryt\'', category: 'verbs' },
  { id: 'v43', russian: 'Закрыть', french: 'Fermer', phonetic: 'Zakryt\'', category: 'verbs' },
  { id: 'v44', russian: 'Любить', french: 'Aimer', phonetic: 'Lyubit\'', category: 'verbs' },
  { id: 'v45', russian: 'Помогать', french: 'Aider', phonetic: 'Pomogat\'', category: 'verbs' },
  { id: 'v46', russian: 'Ждать', french: 'Attendre', phonetic: 'Zhdat\'', category: 'verbs' },
  { id: 'v47', russian: 'Терять', french: 'Perdre', phonetic: 'Teryat\'', category: 'verbs' },
  { id: 'v48', russian: 'Выигрывать', french: 'Gagner', phonetic: 'Vyiigryvat\'', category: 'verbs' },
  { id: 'v49', russian: 'Видеть', french: 'Voir', phonetic: 'Videt\'', category: 'verbs' },
  { id: 'v50', russian: 'Смотреть', french: 'Regarder', phonetic: 'Smotret\'', category: 'verbs' },

  // LES 50 NOMS ESSENTIELS
  { id: 'n1', russian: 'Время', french: 'Temps', phonetic: 'Vremya', category: 'nouns' },
  { id: 'n2', russian: 'День', french: 'Jour', phonetic: 'Den\'', category: 'nouns' },
  { id: 'n3', russian: 'Ночь', french: 'Nuit', phonetic: 'Noch\'', category: 'nouns' },
  { id: 'n4', russian: 'Неделя', french: 'Semaine', phonetic: 'Nedelya', category: 'nouns' },
  { id: 'n5', russian: 'Месяц', french: 'Mois', phonetic: 'Mesyats', category: 'nouns' },
  { id: 'n6', russian: 'Год', french: 'Année', phonetic: 'God', category: 'nouns' },
  { id: 'n7', russian: 'Час', french: 'Heure', phonetic: 'Chas', category: 'nouns' },
  { id: 'n8', russian: 'Минута', french: 'Minute', phonetic: 'Minuta', category: 'nouns' },
  { id: 'n9', russian: 'Утро', french: 'Matin', phonetic: 'Utro', category: 'nouns' },
  { id: 'n10', russian: 'Вечер', french: 'Soir', phonetic: 'Vecher', category: 'nouns' },
  { id: 'n11', russian: 'Сегодня', french: 'Aujourd\'hui', phonetic: 'Segodnya', category: 'nouns' },
  { id: 'n12', russian: 'Завтра', french: 'Demain', phonetic: 'Zavtra', category: 'nouns' },
  { id: 'n13', russian: 'Мужчина', french: 'Homme', phonetic: 'Muzhchina', category: 'nouns' },
  { id: 'n14', russian: 'Женщина', french: 'Femme', phonetic: 'Zhenshchina', category: 'nouns' },
  { id: 'n15', russian: 'Ребенок', french: 'Enfant', phonetic: 'Rebenok', category: 'nouns' },
  { id: 'n16', russian: 'Друг', french: 'Ami', phonetic: 'Drug', category: 'nouns' },
  { id: 'n17', russian: 'Семья', french: 'Famille', phonetic: 'Sem\'ya', category: 'nouns' },
  { id: 'n18', russian: 'Люди', french: 'Gens', phonetic: 'Lyudi', category: 'nouns' },
  { id: 'n19', russian: 'Отец', french: 'Père', phonetic: 'Otets', category: 'nouns' },
  { id: 'n20', russian: 'Мать', french: 'Mère', phonetic: 'Mat\'', category: 'nouns' },
  { id: 'n21', russian: 'Имя', french: 'Nom', phonetic: 'Imya', category: 'nouns' },
  { id: 'n22', russian: 'Дом', french: 'Maison', phonetic: 'Dom', category: 'nouns' },
  { id: 'n23', russian: 'Школа', french: 'École', phonetic: 'Shkola', category: 'nouns' },
  { id: 'n24', russian: 'Работа', french: 'Travail', phonetic: 'Rabota', category: 'nouns' },
  { id: 'n25', russian: 'Страна', french: 'Pays', phonetic: 'Strana', category: 'nouns' },
  { id: 'n26', russian: 'Город', french: 'Ville', phonetic: 'Gorod', category: 'nouns' },
  { id: 'n27', russian: 'Улица', french: 'Rue', phonetic: 'Ulitsa', category: 'nouns' },
  { id: 'n28', russian: 'Мир', french: 'Monde', phonetic: 'Mir', category: 'nouns' },
  { id: 'n29', russian: 'Магазин', french: 'Magasin', phonetic: 'Magazin', category: 'nouns' },
  { id: 'n30', russian: 'Больница', french: 'Hôpital', phonetic: 'Bol\'nitsa', category: 'nouns' },
  { id: 'n31', russian: 'Туалет', french: 'Toilettes', phonetic: 'Tualet', category: 'nouns' },
  { id: 'n32', russian: 'Комната', french: 'Chambre', phonetic: 'Komnata', category: 'nouns' },
  { id: 'n33', russian: 'Вода', french: 'Eau', phonetic: 'Voda', category: 'nouns' },
  { id: 'n34', russian: 'Еда', french: 'Nourriture', phonetic: 'Yeda', category: 'nouns' },
  { id: 'n35', russian: 'Деньги', french: 'Argent', phonetic: 'Den\'gi', category: 'nouns' },
  { id: 'n36', russian: 'Цена', french: 'Prix', phonetic: 'Tsena', category: 'nouns' },
  { id: 'n37', russian: 'Машина', french: 'Voiture', phonetic: 'Mashina', category: 'nouns' },
  { id: 'n38', russian: 'Автобус', french: 'Bus', phonetic: 'Avtobus', category: 'nouns' },
  { id: 'n39', russian: 'Билет', french: 'Billet', phonetic: 'Bilet', category: 'nouns' },
  { id: 'n40', russian: 'Телефон', french: 'Téléphone', phonetic: 'Telefon', category: 'nouns' },
  { id: 'n41', russian: 'Ключ', french: 'Clé', phonetic: 'Klyuch', category: 'nouns' },
  { id: 'n42', russian: 'Кровать', french: 'Lit', phonetic: 'Krovat\'', category: 'nouns' },
  { id: 'n43', russian: 'Одежда', french: 'Vêtement', phonetic: 'Odezhda', category: 'nouns' },
  { id: 'n44', russian: 'Сумка', french: 'Sac', phonetic: 'Sumka', category: 'nouns' },
  { id: 'n45', russian: 'Вещь', french: 'Chose', phonetic: 'Veshch\'', category: 'nouns' },
  { id: 'n46', russian: 'Причина', french: 'Raison', phonetic: 'Prichina', category: 'nouns' },
  { id: 'n47', russian: 'Способ', french: 'Façon', phonetic: 'Sposob', category: 'nouns' },
  { id: 'n48', russian: 'Идея', french: 'Idée', phonetic: 'Ideya', category: 'nouns' },
  { id: 'n49', russian: 'Проблема', french: 'Problème', phonetic: 'Problema', category: 'nouns' },
  { id: 'n50', russian: 'Вопрос', french: 'Question', phonetic: 'Vopros', category: 'nouns' },

  // LES CHIFFRES (POUR APPRENDRE À COMPTER)
  { id: 'num0', russian: 'Ноль', french: 'Zéro', phonetic: 'Nol\'', category: 'numbers' },
  { id: 'num1', russian: 'Один', french: 'Un', phonetic: 'Odin', category: 'numbers' },
  { id: 'num2', russian: 'Два', french: 'Deux', phonetic: 'Dva', category: 'numbers' },
  { id: 'num3', russian: 'Три', french: 'Trois', phonetic: 'Tri', category: 'numbers' },
  { id: 'num4', russian: 'Четыре', french: 'Quatre', phonetic: 'Chetyre', category: 'numbers' },
  { id: 'num5', russian: 'Пять', french: 'Cinq', phonetic: 'Pyat\'', category: 'numbers' },
  { id: 'num6', russian: 'Шесть', french: 'Six', phonetic: 'Shest\'', category: 'numbers' },
  { id: 'num7', russian: 'Семь', french: 'Sept', phonetic: 'Sem\'', category: 'numbers' },
  { id: 'num8', russian: 'Восемь', french: 'Huit', phonetic: 'Vosem\'', category: 'numbers' },
  { id: 'num9', russian: 'Девять', french: 'Neuf', phonetic: 'Devyat\'', category: 'numbers' },
  { id: 'num10', russian: 'Десять', french: 'Dix', phonetic: 'Desyat\'', category: 'numbers' },
  { id: 'num11', russian: 'Одиннадцать', french: 'Onze', phonetic: 'Odinnadtsat\'', category: 'numbers' },
  { id: 'num12', russian: 'Двенадцать', french: 'Douze', phonetic: 'Dvenadtsat\'', category: 'numbers' },
  { id: 'num13', russian: 'Тринадцать', french: 'Treize', phonetic: 'Trinadtsat\'', category: 'numbers' },
  { id: 'num14', russian: 'Четырнадцать', french: 'Quatorze', phonetic: 'Chetyrnadtsat\'', category: 'numbers' },
  { id: 'num15', russian: 'Пятнадцать', french: 'Quinze', phonetic: 'Pyatnadtsat\'', category: 'numbers' },
  { id: 'num16', russian: 'Шестнадцать', french: 'Seize', phonetic: 'Shestnadtsat\'', category: 'numbers' },
  { id: 'num17', russian: 'Семнадцать', french: 'Dix-sept', phonetic: 'Semnadtsat\'', category: 'numbers' },
  { id: 'num18', russian: 'Восемнадцать', french: 'Dix-huit', phonetic: 'Vosemnadtsat\'', category: 'numbers' },
  { id: 'num19', russian: 'Девятнадцать', french: 'Dix-neuf', phonetic: 'Devyatnadtsat\'', category: 'numbers' },
  { id: 'num20', russian: 'Двадцать', french: 'Vingt', phonetic: 'Dvadtsat\'', category: 'numbers' },
  { id: 'num30', russian: 'Тридцать', french: 'Trente', phonetic: 'Tridtsat\'', category: 'numbers' },
  { id: 'num40', russian: 'Сорок', french: 'Quarante', phonetic: 'Sorok', category: 'numbers' },
  { id: 'num50', russian: 'Пятьдесят', french: 'Cinquante', phonetic: 'Pyatdesyat', category: 'numbers' },
  { id: 'num60', russian: 'Шестьдесят', french: 'Soixante', phonetic: 'Shestdesyat', category: 'numbers' },
  { id: 'num70', russian: 'Семьдесят', french: 'Soixante-dix', phonetic: 'Semdesyat', category: 'numbers' },
  { id: 'num80', russian: 'Восемьдесят', french: 'Quatre-vingts', phonetic: 'Vosemdesyat', category: 'numbers' },
  { id: 'num90', russian: 'Девяносто', french: 'Quatre-vingt-dix', phonetic: 'Devyanosto', category: 'numbers' },
  { id: 'num100', russian: 'Сто', french: 'Cent', phonetic: 'Sto', category: 'numbers' },
  { id: 'num1000', russian: 'Тысяча', french: 'Mille', phonetic: 'Tysyacha', category: 'numbers' },

  // LA GLU (50 MOTS)
  // I. Pronoms
  { id: 'g1', russian: 'Я', french: 'Je', phonetic: 'Ya', category: 'glu' },
  { id: 'g2', russian: 'Ты', french: 'Tu', phonetic: 'Ty', category: 'glu' },
  { id: 'g3', russian: 'Вы', french: 'Vous', phonetic: 'Vy', category: 'glu' },
  { id: 'g4', russian: 'Он', french: 'Il', phonetic: 'On', category: 'glu' },
  { id: 'g5', russian: 'Она', french: 'Elle', phonetic: 'Ona', category: 'glu' },
  { id: 'g6', russian: 'Оно', french: 'Ça / Il (neutre)', phonetic: 'Ono', category: 'glu' },
  { id: 'g7', russian: 'Мы', french: 'Nous', phonetic: 'My', category: 'glu' },
  { id: 'g8', russian: 'Они', french: 'Ils / Elles', phonetic: 'Oni', category: 'glu' },
  // II. Questions
  { id: 'g9', russian: 'Что', french: 'Quoi / Que', phonetic: 'Shto', category: 'glu' },
  { id: 'g10', russian: 'Кто', french: 'Qui', phonetic: 'Kto', category: 'glu' },
  { id: 'g11', russian: 'Где', french: 'Où', phonetic: 'Gde', category: 'glu' },
  { id: 'g12', russian: 'Когда', french: 'Quand', phonetic: 'Kogda', category: 'glu' },
  { id: 'g13', russian: 'Почему', french: 'Pourquoi', phonetic: 'Pochemu', category: 'glu' },
  { id: 'g14', russian: 'Как', french: 'Comment', phonetic: 'Kak', category: 'glu' },
  { id: 'g15', russian: 'Сколько', french: 'Combien', phonetic: 'Skol\'ko', category: 'glu' },
  { id: 'g16', russian: 'Который', french: 'Lequel', phonetic: 'Kotoryy', category: 'glu' },
  // III. Logique
  { id: 'g17', russian: 'И', french: 'Et', phonetic: 'I', category: 'glu' },
  { id: 'g18', russian: 'Или', french: 'Ou', phonetic: 'Ili', category: 'glu' },
  { id: 'g19', russian: 'Но', french: 'Mais', phonetic: 'No', category: 'glu' },
  { id: 'g20', russian: 'Если', french: 'Si', phonetic: 'Yesli', category: 'glu' },
  { id: 'g21', russian: 'Потому что', french: 'Parce que', phonetic: 'Potomu shto', category: 'glu' },
  { id: 'g22', russian: 'Поэтому', french: 'Donc / Alors', phonetic: 'Poyetomu', category: 'glu' },
  { id: 'g23', russian: 'Что', french: 'Que (conjonction)', phonetic: 'Shto', category: 'glu' },
  // IV. Prépositions
  { id: 'g24', russian: 'С', french: 'Avec', phonetic: 'S', category: 'glu' },
  { id: 'g25', russian: 'Без', french: 'Sans', phonetic: 'Bez', category: 'glu' },
  { id: 'g26', russian: 'Для', french: 'Pour', phonetic: 'Dlya', category: 'glu' },
  { id: 'g27', russian: 'От', french: 'De / Provenance', phonetic: 'Ot', category: 'glu' },
  { id: 'g28', russian: 'К', french: 'À / Vers', phonetic: 'K', category: 'glu' },
  { id: 'g29', russian: 'В', french: 'Dans', phonetic: 'V', category: 'glu' },
  { id: 'g30', russian: 'На', french: 'Sur', phonetic: 'Na', category: 'glu' },
  { id: 'g31', russian: 'Под', french: 'Sous', phonetic: 'Pod', category: 'glu' },
  { id: 'g32', russian: 'До', french: 'Avant', phonetic: 'Do', category: 'glu' },
  { id: 'g33', russian: 'После', french: 'Après', phonetic: 'Posle', category: 'glu' },
  // V. Temps
  { id: 'g34', russian: 'Сейчас', french: 'Maintenant', phonetic: 'Seychas', category: 'glu' },
  { id: 'g35', russian: 'Позже', french: 'Plus tard', phonetic: 'Pozzhe', category: 'glu' },
  { id: 'g36', russian: 'Всегда', french: 'Toujours', phonetic: 'Vsegda', category: 'glu' },
  { id: 'g37', russian: 'Никогда', french: 'Jamais', phonetic: 'Nikogda', category: 'glu' },
  { id: 'g38', russian: 'Часто', french: 'Souvent', phonetic: 'Chasto', category: 'glu' },
  { id: 'g39', russian: 'Иногда', french: 'Parfois', phonetic: 'Inogda', category: 'glu' },
  { id: 'g40', russian: 'Уже', french: 'Déjà', phonetic: 'Uzhe', category: 'glu' },
  { id: 'g41', russian: 'Ещё', french: 'Encore', phonetic: 'Yeshchyo', category: 'glu' },
  // VI. Quantité
  { id: 'g42', russian: 'Очень', french: 'Très', phonetic: 'Ochen\'', category: 'glu' },
  { id: 'g43', russian: 'Много', french: 'Beaucoup', phonetic: 'Mnogo', category: 'glu' },
  { id: 'g44', russian: 'Немного', french: 'Un peu', phonetic: 'Nemnogo', category: 'glu' },
  { id: 'g45', russian: 'Всё', french: 'Tout', phonetic: 'Vsyo', category: 'glu' },
  { id: 'g46', russian: 'Ничего', french: 'Rien', phonetic: 'Nichego', category: 'glu' },
  { id: 'g47', russian: 'Больше', french: 'Plus', phonetic: 'Bol\'she', category: 'glu' },
  { id: 'g48', russian: 'Меньше', french: 'Moins', phonetic: 'Men\'she', category: 'glu' },
  { id: 'g49', russian: 'Слишком', french: 'Trop', phonetic: 'Slishkom', category: 'glu' },
  // VII. Désigner
  { id: 'g50', russian: 'Это', french: 'Ce / Cette / Ça', phonetic: 'Eto', category: 'glu' },
  { id: 'g51', russian: 'Здесь', french: 'Ici', phonetic: 'Zdes\'', category: 'glu' },
  { id: 'g52', russian: 'Там', french: 'Là-bas', phonetic: 'Tam', category: 'glu' }
];
