
import { RussianWord } from './types';

export const INITIAL_WORDS: RussianWord[] = [
  // VERBS (50)
  { id: 'v1', russian: 'Быть', french: 'Être', phonetic: 'Byt\'', category: 'verbs', example: 'Я хочу быть там.' },
  { id: 'v2', russian: 'Сказать', french: 'Dire', phonetic: 'Skazat\'', category: 'verbs', example: 'Он может сказать правду.' },
  { id: 'v3', russian: 'Мочь', french: 'Pouvoir', phonetic: 'Moch\'', category: 'verbs', example: 'Я могу помочь.' },
  { id: 'v4', russian: 'Говорить', french: 'Parler', phonetic: 'Govorit\'', category: 'verbs', example: 'Я говорю по-русски.' },
  { id: 'v5', russian: 'Знать', french: 'Savoir', phonetic: 'Znat\'', category: 'verbs', example: 'Ты это знаешь?' },
  { id: 'v6', russian: 'Стать', french: 'Devenir', phonetic: 'Stat\'', category: 'verbs', example: 'Он хочет стать врачом.' },
  { id: 'v7', russian: 'Идти', french: 'Aller', phonetic: 'Idti', category: 'verbs', example: 'Мы идем домой.' },
  { id: 'v8', russian: 'Хотеть', french: 'Vouloir', phonetic: 'Khotet\'', category: 'verbs', example: 'Я хочу пить.' },
  { id: 'v9', russian: 'Иметь', french: 'Avoir', phonetic: 'Imet\'', category: 'verbs', example: 'У меня есть время.' },
  { id: 'v10', russian: 'Видеть', french: 'Voir', phonetic: 'Videt\'', category: 'verbs', example: 'Я вижу море.' },
  { id: 'v11', russian: 'Думать', french: 'Penser', phonetic: 'Dumat\'', category: 'verbs' },
  { id: 'v12', russian: 'Сделать', french: 'Faire', phonetic: 'Sdelat\'', category: 'verbs' },
  { id: 'v13', russian: 'Жить', french: 'Vivre', phonetic: 'Zhit\'', category: 'verbs' },
  { id: 'v14', russian: 'Смотреть', french: 'Regarder', phonetic: 'Smotret\'', category: 'verbs' },
  { id: 'v15', russian: 'Работать', french: 'Travailler', phonetic: 'Rabotat\'', category: 'verbs' },
  { id: 'v16', russian: 'Понимать', french: 'Comprendre', phonetic: 'Ponimat\'', category: 'verbs' },
  { id: 'v17', russian: 'Пойти', french: 'Partir', phonetic: 'Poyti', category: 'verbs' },
  { id: 'v18', russian: 'Дать', french: 'Donner', phonetic: 'Dat\'', category: 'verbs' },
  { id: 'v19', russian: 'Писать', french: 'Écrire', phonetic: 'Pisat\'', category: 'verbs' },
  { id: 'v20', russian: 'Читать', french: 'Lire', phonetic: 'Chitat\'', category: 'verbs' },
  { id: 'v21', russian: 'Любить', french: 'Aimer', phonetic: 'Lyubit\'', category: 'verbs' },
  { id: 'v22', russian: 'Просить', french: 'Demander', phonetic: 'Prosit\'', category: 'verbs' },
  { id: 'v23', russian: 'Ждать', french: 'Attendre', phonetic: 'Zhdat\'', category: 'verbs' },
  { id: 'v24', russian: 'Помнить', french: 'Se souvenir', phonetic: 'Pomnit\'', category: 'verbs' },
  { id: 'v25', russian: 'Забыть', french: 'Oublier', phonetic: 'Zabyt\'', category: 'verbs' },
  { id: 'v26', russian: 'Спрашивать', french: 'Interroger', phonetic: 'Sprashivat\'', category: 'verbs' },
  { id: 'v27', russian: 'Приходить', french: 'Arriver', phonetic: 'Prikhodit\'', category: 'verbs' },
  { id: 'v28', russian: 'Брать', french: 'Prendre', phonetic: 'Brat\'', category: 'verbs' },
  { id: 'v29', russian: 'Слушать', french: 'Écouter', phonetic: 'Slushat\'', category: 'verbs' },
  { id: 'v30', russian: 'Чувствовать', french: 'Sentir', phonetic: 'Chuvstvovat\'', category: 'verbs' },
  { id: 'v31', russian: 'Играть', french: 'Jouer', phonetic: 'Igrat\'', category: 'verbs' },
  { id: 'v32', russian: 'Стоять', french: 'Se tenir debout', phonetic: 'Stoyat\'', category: 'verbs' },
  { id: 'v33', russian: 'Сидеть', french: 'S\'asseoir', phonetic: 'Sidet\'', category: 'verbs' },
  { id: 'v34', russian: 'Учиться', french: 'Apprendre', phonetic: 'Uchit\'sya', category: 'verbs' },
  { id: 'v35', russian: 'Купить', french: 'Acheter', phonetic: 'Kupit\'', category: 'verbs' },
  { id: 'v36', russian: 'Пить', french: 'Boire', phonetic: 'Pit\'', category: 'verbs' },
  { id: 'v37', russian: 'Есть', french: 'Manger', phonetic: 'Yest\'', category: 'verbs' },
  { id: 'v38', russian: 'Спать', french: 'Dormir', phonetic: 'Spat\'', category: 'verbs' },
  { id: 'v39', russian: 'Бежать', french: 'Courir', phonetic: 'Bezhat\'', category: 'verbs' },
  { id: 'v40', russian: 'Летать', french: 'Voler (avion)', phonetic: 'Letat\'', category: 'verbs' },
  { id: 'v41', russian: 'Помогать', french: 'Aider', phonetic: 'Pomogat\'', category: 'verbs' },
  { id: 'v42', russian: 'Искать', french: 'Chercher', phonetic: 'Iskat\'', category: 'verbs' },
  { id: 'v43', russian: 'Находить', french: 'Trouver', phonetic: 'Nakhodit\'', category: 'verbs' },
  { id: 'v44', russian: 'Терять', french: 'Perdre', phonetic: 'Teryat\'', category: 'verbs' },
  { id: 'v45', russian: 'Смеяться', french: 'Rire', phonetic: 'Smeyat\'sya', category: 'verbs' },
  { id: 'v46', russian: 'Плакать', french: 'Pleurer', phonetic: 'Plakat\'', category: 'verbs' },
  { id: 'v47', russian: 'Строить', french: 'Construire', phonetic: 'Stroit\'', category: 'verbs' },
  { id: 'v48', russian: 'Верить', french: 'Croire', phonetic: 'Verit\'', category: 'verbs' },
  { id: 'v49', russian: 'Начинать', french: 'Commencer', phonetic: 'Nachinat\'', category: 'verbs' },
  { id: 'v50', russian: 'Кончать', french: 'Finir', phonetic: 'Konchat\'', category: 'verbs' },

  // NOUNS (50)
  { id: 'n1', russian: 'Человек', french: 'Personne', phonetic: 'Chelovek', category: 'nouns' },
  { id: 'n2', russian: 'Год', french: 'Année', phonetic: 'God', category: 'nouns' },
  { id: 'n3', russian: 'Время', french: 'Temps', phonetic: 'Vremya', category: 'nouns' },
  { id: 'n4', russian: 'Дело', french: 'Affaire', phonetic: 'Delo', category: 'nouns' },
  { id: 'n5', russian: 'Жизнь', french: 'Vie', phonetic: 'Zhizn\'', category: 'nouns' },
  { id: 'n6', russian: 'День', french: 'Jour', phonetic: 'Den\'', category: 'nouns' },
  { id: 'n7', russian: 'Рука', french: 'Main', phonetic: 'Ruka', category: 'nouns' },
  { id: 'n8', russian: 'Раз', french: 'Fois', phonetic: 'Raz', category: 'nouns' },
  { id: 'n9', russian: 'Работа', french: 'Travail', phonetic: 'Rabota', category: 'nouns' },
  { id: 'n10', russian: 'Слово', french: 'Mot', phonetic: 'Slovo', category: 'nouns' },
  { id: 'n11', russian: 'Место', french: 'Place', phonetic: 'Mesto', category: 'nouns' },
  { id: 'n12', russian: 'Лицо', french: 'Visage', phonetic: 'Litso', category: 'nouns' },
  { id: 'n13', russian: 'Друг', french: 'Ami', phonetic: 'Drug', category: 'nouns' },
  { id: 'n14', russian: 'Глаз', french: 'Oeil', phonetic: 'Glaz', category: 'nouns' },
  { id: 'n15', russian: 'Дом', french: 'Maison', phonetic: 'Dom', category: 'nouns' },
  { id: 'n16', russian: 'Сторона', french: 'Côté', phonetic: 'Storona', category: 'nouns' },
  { id: 'n17', russian: 'Страна', french: 'Pays', phonetic: 'Strana', category: 'nouns' },
  { id: 'n18', russian: 'Мир', french: 'Monde / Paix', phonetic: 'Mir', category: 'nouns' },
  { id: 'n19', russian: 'Случай', phonetic: 'Sluchay', french: 'Cas', category: 'nouns' },
  { id: 'n20', russian: 'Голова', french: 'Tête', phonetic: 'Golova', category: 'nouns' },
  { id: 'n21', russian: 'Ребенок', french: 'Enfant', phonetic: 'Rebenok', category: 'nouns' },
  { id: 'n22', russian: 'Сила', french: 'Force', phonetic: 'Sila', category: 'nouns' },
  { id: 'n23', russian: 'Конец', french: 'Fin', phonetic: 'Konets', category: 'nouns' },
  { id: 'n24', russian: 'Город', french: 'Ville', phonetic: 'Gorod', category: 'nouns' },
  { id: 'n25', russian: 'Ночь', french: 'Nuit', phonetic: 'Noch\'', category: 'nouns' },
  { id: 'n26', russian: 'Вода', french: 'Eau', phonetic: 'Voda', category: 'nouns' },
  { id: 'n27', russian: 'Мать', french: 'Mère', phonetic: 'Mat\'', category: 'nouns' },
  { id: 'n28', russian: 'Отец', french: 'Père', phonetic: 'Otets', category: 'nouns' },
  { id: 'n29', russian: 'Земля', french: 'Terre', phonetic: 'Zemlya', category: 'nouns' },
  { id: 'n30', russian: 'Машина', french: 'Voiture', phonetic: 'Mashina', category: 'nouns' },
  { id: 'n31', russian: 'Улица', french: 'Rue', phonetic: 'Ulitsa', category: 'nouns' },
  { id: 'n32', russian: 'Книга', french: 'Livre', phonetic: 'Kniga', category: 'nouns' },
  { id: 'n33', russian: 'Деньги', french: 'Argent', phonetic: 'Den\'gi', category: 'nouns' },
  { id: 'n34', russian: 'Стол', french: 'Table', phonetic: 'Stol', category: 'nouns' },
  { id: 'n35', russian: 'Дверь', french: 'Porte', phonetic: 'Dver\'', category: 'nouns' },
  { id: 'n36', russian: 'Окно', french: 'Fenêtre', phonetic: 'Okno', category: 'nouns' },
  { id: 'n37', russian: 'Школа', french: 'École', phonetic: 'Shkola', category: 'nouns' },
  { id: 'n38', russian: 'Семья', french: 'Famille', phonetic: 'Sem\'ya', category: 'nouns' },
  { id: 'n39', russian: 'Вечер', french: 'Soir', phonetic: 'Vecher', category: 'nouns' },
  { id: 'n40', russian: 'Правда', french: 'Vérité', phonetic: 'Pravda', category: 'nouns' },
  { id: 'n41', russian: 'Путь', french: 'Chemin', phonetic: 'Put\'', category: 'nouns' },
  { id: 'n42', russian: 'Душа', french: 'Âme', phonetic: 'Dusha', category: 'nouns' },
  { id: 'n43', russian: 'Язык', french: 'Langue', phonetic: 'Yazyk', category: 'nouns' },
  { id: 'n44', russian: 'Любовь', french: 'Amour', phonetic: 'Lyubov\'', category: 'nouns' },
  { id: 'n45', russian: 'Вопрос', french: 'Question', phonetic: 'Vopros', category: 'nouns' },
  { id: 'n46', russian: 'Ответ', french: 'Réponse', phonetic: 'Otvet', category: 'nouns' },
  { id: 'n47', russian: 'Голос', french: 'Voix', phonetic: 'Golos', category: 'nouns' },
  { id: 'n48', russian: 'Вид', french: 'Vue / Aspect', phonetic: 'Vid', category: 'nouns' },
  { id: 'n49', russian: 'Солнце', french: 'Soleil', phonetic: 'Solntse', category: 'nouns' },
  { id: 'n50', russian: 'Небо', french: 'Ciel', phonetic: 'Nebo', category: 'nouns' }
];
